### ISSUE TITLE
Keys should be uploaded after activation, not before

### ISSUE THREAD

**Issue by CitadelCore** [zhaofengli/colmena#10]
Running into an issue with new machines because I have a module that creates a user and group. Seems like the keys are uploaded before activation, which means the `chown` can fail:

```
[ERROR] Deployment to [redacted] failed. Last 3 lines of logs:
[ERROR] sh: -c: option requires an argument
[ERROR] chown: invalid user: ‘vault-agent:vault-agent’
[ERROR]
```

**Comment by zhaofengli** [comment]
Oops, missed this one. We need to take more time to look at this. I initially thought uploading the keys before activation was the correct way, since the new profile may rely on the keys (e.g., service restarts/reloads will fail without them).

Just took a look, and NixOps and Morph both upload keys before activation. [NixOps' solution](https://github.com/NixOS/nixops/blob/23db83fc91952d2dbcc64b8aa1ac16f8c8f45bed/nixops/backends/__init__.py#L417-L427) is to do a UID/GID look up, and keep the file owned by root if the specified user/group doesn't exist yet. I'm not seeing any special handling of this case in Morph, but I may have missed something.

I'm not really sure what would be the correct solution here. We can potentially make this part of the activationScripts and have the temporary key files moved to the correct destinations after user/group changes are applied but before any services get restarted. But this sounds particularly hacky to me.

**Comment by tv42** [comment]
One alternative, to avoid needing to do this work, is to move toward a world where the secrets are always shipped only readable by root, and then systemd `LoadCredential=` and `$CREDENTIALS_DIRECTORY` to pass them to the place of consumption, letting that manage the owning user. This also works with `DynamicUser=yes` services, sandboxes, etc.

https://www.freedesktop.org/software/systemd/man/systemd.exec.html#Credentials

**Comment by zhaofengli** [comment]
Just a note that [morph](https://github.com/DBCDK/morph/pull/158) now makes this configurable per-secret via an option. We could do something similar and perform the key deployment twice for the two sets of keys depending on a toggle.

**Comment by zhaofengli** [comment]
Let's just start simple and implement morph's `deployment.keys.<name>.uploadAt`.
