### ISSUE TITLE
Flake support 

### ISSUE THREAD

**Issue by roosemberth** [zhaofengli/colmena#11]
I may have overlooked something but I couldn't find any references on how to use flakes, moreover the nixpkgs meta suggests the inputs are hardcoded.

Are there plans to add flake support?

**Comment by CitadelCore** [comment]
So I did some thinking about what would be required to implement this.

1. Colmena itself would be made a flake so that it can be added as a dependency in hive flakes.
2. This flake would need to expose an output with the NixOS modules (i.e. for keys and deployment parameters) and a couple library functions that would allow the hive flake to produce the correct outputs.
3. Instantiation process would be relatively similar, with `nix eval` instead of `nix-instantiate`. 

A good reference is [deploy-rs](https://github.com/serokell/deploy-rs), which is one of the only deployment tools out there that actually supports flakes well.

I'm currently working on a prototype in [this branch](https://github.com/ArctarusLimited/colmena/tree/feat/flake-support) (although I really don't have much experience with Rust, so we'll see how that goes...)

**Comment by CitadelCore** [comment]
See #19.

**Comment by zhaofengli** [comment]
Just pushed some preliminary support for Flakes (see README.md). Please, give it a try! Thanks to @CitadelCore for getting the whole thing started.

**Comment by zhaofengli** [comment]
Closing since Flakes support has been in place for a while. I'm actively using it in 4 different clusters.
