### ISSUE TITLE
bug: cannot apply without `--impure`

### ISSUE THREAD

**Issue by nrdxp** [zhaofengli/colmena#202]
As of a recent update of nixos-unstable (maybe 2-3 weeks ago), I haven't been able to run `colmena apply` without adding the `--impure` argument due to colmena wanting to make some lockfile changes to it's "Internal Colmena Expressions" flake that get's placed in the `/tmp` directory.

I am a bit surprised nobody else reported this, so perhaps there is something about my particular flake (which is quite complex at this point) that could be causing this, but in any case, since it seems to be an internal colmena function to create this temporary flake, I figured it was worth reporting.

It may be as simply as running a `nix flake lock` on this temporary flake before doing anything else, but I don't understand enough what colmena is doing (yet) to say for sure.

**Comment by xddxdd** [comment]
I also saw a similar issue. This happens if I made some changes to my config without committing everything. The exact error message is `cannot update unlocked flake input 'hive' in pure mode`.

I patched colmena to disable its use of pure mode: https://github.com/xddxdd/nixos-config/blob/11358a9fddadb544e85a2ecba1aaa987023e98ed/patches/colmena-disable-pure-eval.patch

But I'm not sure if this is the correct approach.

**Comment by nrdxp** [comment]
Ah yeah, I usually have a least a few uncommitted changes laying around so I didn't even think about that, but you are right, if I stash everything the error goes away. This seems to be a different definition of "pure" than Nix itself, which is perfectly happy to build an unclean tree in "pure" eval mode itself, and until recently it seems, so was Colmena

**Comment by msanft** [comment]
Running into the same issue since the last update of my flake.

**Comment by nrdxp** [comment]
I would have imagined that this line would take care of locking the flake:
https://github.com/zhaofengli/colmena/blob/main/src/nix/hive/assets.rs#L55

So something more complex must be going on :thinking:

**Comment by Silver-Golden** [comment]
Also impacting us, was a pita to track down this issue as well

**Comment by Pamplemousse** [comment]
Running into the same issue since bumping my `nixpkgs`'s input to `24.05`...

**Comment by aanderse** [comment]
> Running into the same issue since bumping my `nixpkgs` input to `24.05`...

i am as well - anyone work up a fix for this in the code at all yet?

**Comment by 9R** [comment]
I also was experiencing this issue after i updated to 24.05. Recently I switch to lix and I just noticed that I again can build without `--impure`.

**Comment by Silver-Golden** [comment]
I also switched to lix recetnyl as well, so just tested if that was responsible, seems not.  
I am on ``24.11`` (``unstable``) for nixos and ``0.5.0-pre`` for colmena.

```
[silver@ananke:/mnt/c/Dev/Personal/Nix/Personal]$ nixos-version
24.11pre-git (Vicuna)

[silver@ananke:/mnt/c/Dev/Personal/Nix/Personal]$ nix --version
nix (Lix, like Nix) 2.91.0-dev-pre20240717-6856720

[silver@ananke:/mnt/c/Dev/Personal/Nix/Personal]$ nixos-version
24.11pre-git (Vicuna)

[silver@ananke:/mnt/c/Dev/Personal/Nix/Personal]$ colmena --version
Colmena 0.5.0-pre
```

**Comment by johnalotoski** [comment]
For me, the relatively new `--impure` requirement is due to `nix` changes as of version `2.21.0` where prior to [this](https://github.com/NixOS/nix/commit/071dd2b3a4e6c0b2106f1b6f14ec26e153d97446) commit dirty worktrees for git inputs were allowed due to buggy behavior that got fixed.

All the extra verbosity using `--impure` can't seem to be turned off by any nix options or switches.  Perhaps nix could add a flag in the future to turn off output for [flake input changes](https://github.com/NixOS/nix/blob/master/src/libflake/flake/lockfile.cc#L323-L353) which get printed to stderr.

In the meantime, the following is the best I've been able to come up in bash, where color is preserved and only a few extra lines are shown compared to prior behavior:
```bash
  CLICOLOR_FORCE=1 colmena apply --impure --verbose --color always --on "$MACHINE" \
    1> >(sed --regex '/.*colmena-assets-.*/ d; /.*• Added input .*/ {N;d}' >&1) \
    2> >(sed --regex '/.*colmena-assets-.*/ d; /• Added input .*/ {N;d}' >&2)
```

**Comment by zhaofengli** [comment]
The current method of generating a temporary flake and evaluating with `builtins.getFlake` has always been a source of problems 🙈 Been procrastinating on this for a long time, but with NixOS 24.11 releasing soon carrying Nix 2.24 as the default, it's finally time to fix it.

#228 adds support for evaluating with `nix eval` directly so pure evaluation works again with newer Nix. It's not finished but already lets me upgrade to Nix 2.24 in my own setup.
