### ISSUE TITLE
Prevent apply-local without root access by default

### ISSUE THREAD

**Issue by brizzbuzz** [zhaofengli/colmena#203]
Hey :wave: Loving colmena so far, thanks so much for this tool.

I'm wondering about the behavior for `apply-local`, and whether it should enforced that root access is required by default, rather than just a warning. 

Would it make more sense for `colmena apply-local` to have a flag such as `--without-root` for the rare case when this behavior is desired?  

Not a big deal either way, I've just carelessly run `colmena apply-local` several times without root access and wondered why my build as failed :)

**Comment by NeverBehave** [comment]
Context: we do have flag `--sudo` https://colmena.cli.rs/unstable/features/apply-local.html?highlight=sudo#local-deployment

so the idea here is to always try sudo?

**Comment by NeverBehave** [comment]
I guess, since sudo is more or less dangerous to interact with without user consent, by default we don't try it but give out warnings (? Not sure whether we have one) and provide this flag as an option.

If we do not have such warning/suggestions on failure we have add one, if so I would prefer to keep current behavior.

**Comment by brizzbuzz** [comment]
yep there are warnings :) I think i'll close this... thinking more about the behavior I think how it is now makes the most sense, and realistically this command will be either behind an alias or a build script most of the time anyway
