### ISSUE TITLE
running nix-shell on target machine

### ISSUE THREAD

**Issue by aanderse** [zhaofengli/colmena#32]
What is the *best* way to make `nix-shell` use `meta.nixpkgs` on target machines using `colmena`?

**Comment by zhaofengli** [comment]
Also interested to see what other people are doing. On my machines, I do `nix.nixPath = [ "nixpkgs=${pkgs.path}" ];`.

**Comment by aanderse** [comment]
Great! Thanks @zhaofengli! I'll use that.

**Comment by zhaofengli** [comment]
For future reference, [this solution](https://matrix.to/#/!KqkRjyTEzAGRiZFBYT:nixos.org/$Q-1pzOKZQv1BcL1gWsObIZnT0P6Gw4rH6IvEj_jGZqI?via=nixos.org&via=matrix.org&via=tchncs.de) by @ElvishJerricco is better because there is no need to restart existing shell sessions to use the new NIX_PATH. It works by using a layer of indirection:

```nix
{
  nix.registry = lib.mapAttrs (n: flake: { inherit flake; }) inputs;
  environment.etc = lib.mapAttrs' (name: flake: {
    name = "nix/inputs/${name}";
    value.source = flake.outPath;
  }) inputs;
  nix.nixPath = [ "/etc/nix/inputs" ];
}
```
