### ISSUE TITLE
Add `${name}-key.service` unit files for `deployment.keys` entries

### ISSUE THREAD

**Issue by CRTified** [zhaofengli/colmena#48]
This is relevant for `nixops`-compability, as `nixops` uses these unit files as an indicator for other services that the key is available.
It's also helpful to prevent services from starting if the key is not available, e.g. in the case of unexpected (or in general external) reboots.

The [definition in `nixops`](https://github.com/NixOS/nixops/blob/ce1c57ec104636954296c229468bb65fa4ec7f8d/nix/keys.nix#L234-L262) uses `inotifywait`, but a [path unit](https://www.freedesktop.org/software/systemd/man/systemd.path.html) might be the more elegant way to solve this.

**Comment by phaer** [comment]
Ah, just saw that you already created an issue. I've never used nixops, but use the following with my colmena deployments:

```
  let makeSecretPathUnit = name: _value:
    lib.nameValuePair "secret-${name}" {
      wantedBy = [ "multi-user.target" ];
      pathConfig =
        let
          path = "/run/keys/${name}";
        in
        {
          PathExists = path;
          PathChanged = path;
        };
    };
   in lib.mapAttrs' makeSecretPathUnit deployment.secrets;
```

(slightly adapted, because i am using an extra layer in between, which allows me to use secrets with templating)

**Comment by zhaofengli** [comment]
I just took a look at this, and path units alone aren't enough to replicate the NixOps behavior because the bound units [aren't automatically deactivated](https://github.com/systemd/systemd/issues/3642) when the watched paths disappear so I ended up doing an `inotifywait -e delete_self` :neutral_face:

Could you test whether #51 solves the problem?
